services:
  app:
    image: ghcr.io/seppukusoft/2026modelserver:latest
    container_name: election-model
    restart: unless-stopped

    environment:
      NODE_ENV: production
    env_file:
      - .env