services:
  app:
    image: ghcr.io/seppukusoft/2026modelserver:sha256-84edc9078e827e7f52100b261db12a0d0387562afd6564b5158f3ef235a9a5e4.sig
    container_name: election-model
    restart: unless-stopped

    environment:
      NODE_ENV: production
    env_file:
      - .env